import type { ArchGraph } from "@/types/graph";

export const MOCK_CLICKY: ArchGraph = {
  repoUrl: "https://github.com/farzaa/clicky",
  repoName: "farzaa/clicky",
  commitSha: "main",
  analyzedAt: new Date().toISOString(),
  modules: [
    {
      id: "app-entry",
      name: "App Entry Point",
      files: ["leanring-buddy/leanring_buddyApp.swift"],
      category: "core",
      responsibility: "SwiftUI @main App struct. Delegates to CompanionAppDelegate which creates managers on launch.",
      keyTypes: ["leanring_buddyApp", "CompanionAppDelegate"],
      keyMethods: ["applicationDidFinishLaunching()"],
      lineCount: 89,
    },
    {
      id: "companion-manager",
      name: "CompanionManager",
      files: ["leanring-buddy/CompanionManager.swift"],
      category: "core",
      responsibility: "Central state machine coordinating all subsystems. Manages a 4-state voice interaction loop: idle → listening → processing → responding.",
      keyTypes: ["CompanionManager", "CompanionVoiceState", "PointingParseResult"],
      keyMethods: [
        "start()",
        "handleShortcutTransition()",
        "sendTranscriptToClaudeWithScreenshot()",
        "parsePointingCoordinates(from:)",
      ],
      lineCount: 1026,
    },
    {
      id: "ptt-monitor",
      name: "Push-to-Talk Monitor",
      files: ["leanring-buddy/GlobalPushToTalkShortcutMonitor.swift"],
      category: "voice",
      responsibility: "Creates a listen-only CGEvent tap to detect system-wide ctrl+option press/release, even when the app isn't focused.",
      keyTypes: ["GlobalPushToTalkShortcutMonitor", "BuddyPushToTalkShortcut"],
      keyMethods: ["shortcutTransition()"],
      lineCount: 132,
    },
    {
      id: "dictation-manager",
      name: "Dictation Manager",
      files: ["leanring-buddy/BuddyDictationManager.swift"],
      category: "voice",
      responsibility: "Manages push-to-talk lifecycle: permission checks, AVAudioEngine setup, provider routing, and final transcript delivery.",
      keyTypes: ["BuddyDictationManager"],
      keyMethods: [
        "startPushToTalkFromKeyboardShortcut()",
        "stopPushToTalkFromKeyboardShortcut()",
        "requestFinalTranscript()",
      ],
      lineCount: 866,
    },
    {
      id: "assemblyai-provider",
      name: "AssemblyAI Provider",
      files: ["leanring-buddy/AssemblyAIStreamingTranscriptionProvider.swift"],
      category: "voice",
      responsibility: "Primary STT provider. Fetches a 480s token from the Worker, opens AssemblyAI v3 websocket, streams PCM16 audio in real time.",
      keyTypes: ["AssemblyAIStreamingTranscriptionProvider", "AssemblyAIStreamingTranscriptionSession"],
      keyMethods: ["startStreamingSession()", "appendAudioBuffer()"],
      lineCount: 478,
    },
    {
      id: "openai-stt",
      name: "OpenAI STT",
      files: ["leanring-buddy/OpenAIAudioTranscriptionProvider.swift"],
      category: "voice",
      responsibility: "Upload-based STT fallback. Buffers audio as PCM16, builds WAV on key release, uploads to OpenAI transcription API.",
      keyTypes: ["OpenAIAudioTranscriptionProvider"],
      keyMethods: ["startStreamingSession()", "requestFinalTranscript()"],
      lineCount: 317,
    },
    {
      id: "apple-speech",
      name: "Apple Speech",
      files: ["leanring-buddy/AppleSpeechTranscriptionProvider.swift"],
      category: "voice",
      responsibility: "Local-only STT fallback using Apple's SFSpeechRecognizer. No API key needed — always available.",
      keyTypes: ["AppleSpeechTranscriptionProvider"],
      keyMethods: ["startStreamingSession()"],
      lineCount: 147,
    },
    {
      id: "transcription-protocol",
      name: "Transcription Protocol",
      files: ["leanring-buddy/BuddyTranscriptionProvider.swift"],
      category: "voice",
      responsibility: "Defines the pluggable STT interface. BuddyTranscriptionProviderFactory selects provider via Info.plist config with cascading fallback.",
      keyTypes: ["BuddyStreamingTranscriptionSession", "BuddyTranscriptionProvider", "BuddyTranscriptionProviderFactory"],
      keyMethods: ["startStreamingSession()", "requestFinalTranscript()"],
      lineCount: 100,
    },
    {
      id: "audio-conversion",
      name: "Audio Conversion",
      files: ["leanring-buddy/BuddyAudioConversionSupport.swift"],
      category: "utility",
      responsibility: "Converts AVAudioPCMBuffer from mic to PCM16 mono. Builds WAV files for upload-based providers.",
      keyTypes: ["BuddyPCM16AudioConverter", "BuddyWAVFileBuilder"],
      keyMethods: ["convert()", "buildWAVData()"],
      lineCount: 108,
    },
    {
      id: "overlay-manager",
      name: "Overlay Window Manager",
      files: ["leanring-buddy/OverlayWindow.swift"],
      category: "visual",
      responsibility: "Creates one transparent, click-through, always-on-top NSWindow per connected monitor. Manages lifecycle as displays connect/disconnect.",
      keyTypes: ["OverlayWindow", "OverlayWindowManager", "BuddyNavigationMode"],
      keyMethods: ["createOverlays()", "destroyOverlays()"],
      lineCount: 881,
    },
    {
      id: "blue-cursor",
      name: "Blue Cursor View",
      files: ["leanring-buddy/OverlayWindow.swift"],
      category: "visual",
      responsibility: "SwiftUI view rendering a blue triangle beside the mouse. Modes: idle (triangle), listening (waveform), processing (spinner). Flies to targets via quadratic bezier animation.",
      keyTypes: ["BlueCursorView", "Triangle"],
      keyMethods: ["startNavigatingToElement()", "animateBezierFlightArc()"],
      lineCount: 400,
    },
    {
      id: "menu-bar",
      name: "Menu Bar Panel",
      files: ["leanring-buddy/MenuBarPanelManager.swift"],
      category: "visual",
      responsibility: "Creates NSStatusItem with triangle icon in macOS menu bar. Uses KeyablePanel (NSPanel subclass) for text field focus.",
      keyTypes: ["MenuBarPanelManager", "KeyablePanel"],
      keyMethods: ["togglePanel()", "dismissPanel()"],
      lineCount: 243,
    },
    {
      id: "panel-view",
      name: "CompanionPanelView",
      files: ["leanring-buddy/CompanionPanelView.swift"],
      category: "visual",
      responsibility: "SwiftUI dropdown panel UI: status dot, model picker (Sonnet/Opus), permission buttons, start/onboarding, feedback, quit.",
      keyTypes: ["CompanionPanelView"],
      keyMethods: [],
      lineCount: 761,
    },
    {
      id: "claude-client",
      name: "Claude API Client",
      files: ["leanring-buddy/ClaudeAPI.swift"],
      category: "api-client",
      responsibility: "Sends vision requests (multi-image + conversation history) to Claude via Worker proxy. SSE streaming with content_block_delta parsing.",
      keyTypes: ["ClaudeAPI"],
      keyMethods: ["analyzeImageStreaming()", "analyzeImage()", "detectImageMediaType()"],
      lineCount: 291,
    },
    {
      id: "tts-client",
      name: "ElevenLabs TTS",
      files: ["leanring-buddy/ElevenLabsTTSClient.swift"],
      category: "api-client",
      responsibility: "Sends text to Worker /tts endpoint. Downloads full audio, plays via AVAudioPlayer. Model: eleven_flash_v2_5.",
      keyTypes: ["ElevenLabsTTSClient"],
      keyMethods: ["speakText()", "stopPlayback()"],
      lineCount: 81,
    },
    {
      id: "screen-capture",
      name: "Screen Capture",
      files: ["leanring-buddy/CompanionScreenCaptureUtility.swift"],
      category: "utility",
      responsibility: "Captures all monitors as JPEG via ScreenCaptureKit. Excludes own windows, caps at 1280px, labels screens for Claude context.",
      keyTypes: ["CompanionScreenCapture", "CompanionScreenCaptureUtility"],
      keyMethods: ["captureAllScreensAsJPEG()"],
      lineCount: 132,
    },
    {
      id: "permissions",
      name: "Permission Manager",
      files: ["leanring-buddy/WindowPositionManager.swift"],
      category: "utility",
      responsibility: "Static helpers for checking/requesting macOS permissions: Accessibility, Screen Recording, Microphone. Opens System Settings URLs.",
      keyTypes: ["WindowPositionManager"],
      keyMethods: ["checkAccessibility()", "checkScreenRecording()", "requestMicrophoneAccess()"],
      lineCount: 262,
    },
    {
      id: "analytics",
      name: "PostHog Analytics",
      files: ["leanring-buddy/ClickyAnalytics.swift"],
      category: "utility",
      responsibility: "Wraps PostHog SDK. Tracks: app_opened, onboarding, permissions, push_to_talk, messages, errors.",
      keyTypes: ["ClickyAnalytics"],
      keyMethods: ["track()"],
      lineCount: 121,
    },
    {
      id: "design-system",
      name: "Design System",
      files: ["leanring-buddy/DesignSystem.swift"],
      category: "utility",
      responsibility: "DS namespace with all design tokens: Colors (dark palette), CornerRadius, button styles, hover effects.",
      keyTypes: ["DS", "DS.Colors", "DS.CornerRadius"],
      keyMethods: [],
      lineCount: 880,
    },
    {
      id: "chat-route",
      name: "/chat",
      files: ["worker/src/index.ts"],
      category: "proxy",
      responsibility: "Proxies POST to api.anthropic.com/v1/messages. Injects ANTHROPIC_API_KEY. Streams SSE response back to app.",
      keyTypes: [],
      keyMethods: [],
      lineCount: 40,
    },
    {
      id: "tts-route",
      name: "/tts",
      files: ["worker/src/index.ts"],
      category: "proxy",
      responsibility: "Proxies POST to ElevenLabs TTS API. Injects ELEVENLABS_API_KEY. Streams audio back.",
      keyTypes: [],
      keyMethods: [],
      lineCount: 30,
    },
    {
      id: "token-route",
      name: "/transcribe-token",
      files: ["worker/src/index.ts"],
      category: "proxy",
      responsibility: "Fetches 480s streaming token from AssemblyAI. App uses token to open direct websocket.",
      keyTypes: [],
      keyMethods: [],
      lineCount: 20,
    },
    {
      id: "anthropic-api",
      name: "Anthropic API",
      files: [],
      category: "external",
      responsibility: "Claude Sonnet/Opus vision models. Returns streaming text with optional [POINT:x,y:label:screenN] tags for element pointing.",
      keyTypes: [],
      keyMethods: [],
    },
    {
      id: "elevenlabs-api",
      name: "ElevenLabs API",
      files: [],
      category: "external",
      responsibility: "Text-to-speech with eleven_flash_v2_5 model. Returns audio data for playback.",
      keyTypes: [],
      keyMethods: [],
    },
    {
      id: "assemblyai-api",
      name: "AssemblyAI API",
      files: [],
      category: "external",
      responsibility: "Real-time streaming speech-to-text via WebSocket v3 protocol. Turn-based transcripts with partial results.",
      keyTypes: [],
      keyMethods: [],
    },
  ],
  edges: [
    // Core ownership
    { from: "app-entry", to: "companion-manager", type: "owns", label: "creates on launch" },
    { from: "app-entry", to: "menu-bar", type: "owns", label: "creates on launch" },

    // CompanionManager owns subsystems
    { from: "companion-manager", to: "ptt-monitor", type: "owns" },
    { from: "companion-manager", to: "dictation-manager", type: "owns" },
    { from: "companion-manager", to: "overlay-manager", type: "owns" },
    { from: "companion-manager", to: "claude-client", type: "owns" },
    { from: "companion-manager", to: "tts-client", type: "owns" },
    { from: "companion-manager", to: "screen-capture", type: "depends" },
    { from: "companion-manager", to: "analytics", type: "weak" },
    { from: "companion-manager", to: "permissions", type: "weak" },

    // Voice pipeline
    { from: "dictation-manager", to: "transcription-protocol", type: "depends" },
    { from: "transcription-protocol", to: "assemblyai-provider", type: "depends", label: "primary" },
    { from: "transcription-protocol", to: "openai-stt", type: "depends", label: "fallback" },
    { from: "transcription-protocol", to: "apple-speech", type: "depends", label: "fallback" },
    { from: "dictation-manager", to: "audio-conversion", type: "depends" },
    { from: "assemblyai-provider", to: "audio-conversion", type: "depends" },
    { from: "openai-stt", to: "audio-conversion", type: "depends" },

    // Visual system
    { from: "overlay-manager", to: "blue-cursor", type: "owns" },
    { from: "menu-bar", to: "panel-view", type: "owns" },
    { from: "panel-view", to: "design-system", type: "weak" },

    // API client → Proxy → External
    { from: "claude-client", to: "chat-route", type: "dataflow", label: "POST stream" },
    { from: "tts-client", to: "tts-route", type: "dataflow", label: "POST audio" },
    { from: "assemblyai-provider", to: "token-route", type: "dataflow", label: "GET token" },

    { from: "chat-route", to: "anthropic-api", type: "dataflow" },
    { from: "tts-route", to: "elevenlabs-api", type: "dataflow" },
    { from: "token-route", to: "assemblyai-api", type: "dataflow" },
  ],
};
